name: Testing
on:
  push:
    branches: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Begin building
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:coverage

      - name: Run build
        run: yarn build
